### PR TITLE
updated lessons

### PR DESCRIPTION
**Pull request by lwasser**
@tracykteal where do you want the new rmd files? the lessons now are in the main dir.

### CODE REVIEW

**Comment by tracykteal** [comment]
Ultimately they need to go in _episodes_rmd. OK if that's in this PR or another one though

**Comment by lwasser** [comment]
ok - moved them. you can merge this.

**Comment by lwasser** [comment]
unless there is someting else wrong!

**Comment by tracykteal** [comment]
looks good! thanks!

**Pull request merged**
